version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
