repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
      - id: golangci-lint

  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go mod tidy
        entry: sh -c 'go mod tidy && git diff --exit-code go.mod go.sum'
        language: system
        pass_filenames: false
        files: \.go$|go\.mod$|go\.sum$

      - id: go-fmt
        name: gofmt
        entry: gofmt -l -w
        language: system
        types: [go]
