repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
      - id: golangci-lint

  - repo: local
    hooks:
      - id: go-fmt
        name: gofmt
        entry: gofmt -l -w
        language: system
        types: [go]
