// Package proposal implements the proposal analysis engine for rootline fix.
//
// It analyzes validation errors across multiple records and generates
// actionable proposals: extend enums, correct typos, add missing fields,
// migrate body values to frontmatter, and infer from child documents.
package proposal

import (
	"fmt"
	"strings"

	"github.com/pablontiv/rootline/internal/extract"
	"github.com/pablontiv/rootline/internal/rules"
)

// Type identifies the kind of proposal.
type Type string

const (
	ExtendEnum   Type = "extend_enum"
	MigrateValue Type = "migrate_value"
	CorrectValue Type = "correct_value"
	AddField     Type = "add_field"
)

// Proposal represents a suggested fix for one or more validation errors.
type Proposal struct {
	Type        Type     `json:"type"`
	Field       string   `json:"field"`
	Description string   `json:"description"`
	Paths       []string `json:"paths"`
	Value       string   `json:"value,omitempty"`
	From        string   `json:"from,omitempty"`
	To          string   `json:"to,omitempty"`
	WikiLinks   []string `json:"wiki_links,omitempty"`
}

// Report holds all proposals generated by Analyze.
type Report struct {
	Version   int        `json:"version"`
	Kind      string     `json:"kind"`
	Proposals []Proposal `json:"proposals"`
	Summary   Summary    `json:"summary"`
}

// Summary holds aggregate counts for a report.
type Summary struct {
	Total        int `json:"total"`
	ExtendEnum   int `json:"extend_enum"`
	MigrateValue int `json:"migrate_value"`
	CorrectValue int `json:"correct_value"`
	AddField     int `json:"add_field"`
}

// Analyze runs all detectors against validation errors and returns a Report.
func Analyze(records []*extract.Record, effective *rules.StemFile, errs map[string][]rules.ValidationError) *Report {
	var proposals []Proposal

	if effective != nil && len(errs) > 0 {
		proposals = append(proposals, detectExtendEnum(effective, errs)...)
		proposals = append(proposals, detectMigrateValue(effective, errs)...)
		proposals = append(proposals, detectCorrectValue(effective, errs)...)
		proposals = append(proposals, detectAddField(effective, errs)...)
	}

	summary := Summary{Total: len(proposals)}
	for _, p := range proposals {
		switch p.Type {
		case ExtendEnum:
			summary.ExtendEnum++
		case MigrateValue:
			summary.MigrateValue++
		case CorrectValue:
			summary.CorrectValue++
		case AddField:
			summary.AddField++
		}
	}

	return &Report{
		Version:   1,
		Kind:      "rootline/proposals",
		Proposals: proposals,
		Summary:   summary,
	}
}

// detectExtendEnum finds enum values rejected by validation that appear in
// N >= 2 records, suggesting the .stem schema should be extended.
func detectExtendEnum(effective *rules.StemFile, errs map[string][]rules.ValidationError) []Proposal {
	// Collect invalid enum values per field.
	type fieldValue struct {
		field string
		value string
	}
	counts := make(map[fieldValue][]string) // fieldValue -> list of paths

	for path, pathErrs := range errs {
		for _, e := range pathErrs {
			if e.Rule != "enum" {
				continue
			}
			sf, ok := effective.Schema[e.Field]
			if !ok {
				continue
			}
			// Extract the actual invalid value from the error message.
			// The error format is: "value %q not in allowed values: ..."
			val := extractEnumValue(e.Message, sf.Values)
			if val != "" {
				fv := fieldValue{field: e.Field, value: val}
				counts[fv] = append(counts[fv], path)
			}
		}
	}

	var proposals []Proposal
	for fv, paths := range counts {
		if len(paths) < 2 {
			continue
		}
		proposals = append(proposals, Proposal{
			Type:        ExtendEnum,
			Field:       fv.field,
			Description: fmt.Sprintf("value %q appears in %d records; consider adding to .stem enum", fv.value, len(paths)),
			Paths:       paths,
			Value:       fv.value,
		})
	}
	return proposals
}

// detectMigrateValue finds enum errors where the value contains structured
// information like "Pending (blocked by T001)" and proposes migration.
func detectMigrateValue(effective *rules.StemFile, errs map[string][]rules.ValidationError) []Proposal {
	var proposals []Proposal

	for path, pathErrs := range errs {
		for _, e := range pathErrs {
			if e.Rule != "enum" {
				continue
			}
			sf, ok := effective.Schema[e.Field]
			if !ok || len(sf.Values) == 0 {
				continue
			}
			val := extractEnumValue(e.Message, sf.Values)
			if val == "" {
				continue
			}
			base, targets, notes := ParseBlockingInfo(val)
			if len(targets) == 0 && len(notes) == 0 {
				continue // No parenthetical info — not a migrate_value candidate
			}

			// Find the closest valid enum value for the base.
			newValue := closestMatch(base, sf.Values)
			var wikiLinks []string
			for _, t := range targets {
				wikiLinks = append(wikiLinks, "[[blocks:"+t+"]]")
			}

			desc := fmt.Sprintf("migrate %q to %q", val, newValue)
			if len(notes) > 0 {
				desc += fmt.Sprintf(" (notes: %s)", strings.Join(notes, ", "))
			}

			proposals = append(proposals, Proposal{
				Type:        MigrateValue,
				Field:       e.Field,
				Description: desc,
				Paths:       []string{path},
				From:        val,
				To:          newValue,
				WikiLinks:   wikiLinks,
			})
		}
	}
	return proposals
}

// detectCorrectValue finds enum errors where the value is close to a valid one.
func detectCorrectValue(effective *rules.StemFile, errs map[string][]rules.ValidationError) []Proposal {
	var proposals []Proposal

	for path, pathErrs := range errs {
		for _, e := range pathErrs {
			if e.Rule != "enum" {
				continue
			}
			sf, ok := effective.Schema[e.Field]
			if !ok || len(sf.Values) == 0 {
				continue
			}
			val := extractEnumValue(e.Message, sf.Values)
			if val == "" {
				continue
			}
			closest := closestMatch(val, sf.Values)
			if closest != "" && closest != val {
				proposals = append(proposals, Proposal{
					Type:        CorrectValue,
					Field:       e.Field,
					Description: fmt.Sprintf("value %q is close to %q", val, closest),
					Paths:       []string{path},
					From:        val,
					To:          closest,
				})
			}
		}
	}
	return proposals
}

// detectAddField finds required fields that are missing from records.
func detectAddField(effective *rules.StemFile, errs map[string][]rules.ValidationError) []Proposal {
	var proposals []Proposal

	for path, pathErrs := range errs {
		for _, e := range pathErrs {
			if e.Rule != "required" {
				continue
			}
			sf, ok := effective.Schema[e.Field]
			if !ok {
				continue
			}
			defaultVal := sf.Default
			if defaultVal == "" && len(sf.Values) > 0 {
				defaultVal = sf.Values[0]
			}
			proposals = append(proposals, Proposal{
				Type:        AddField,
				Field:       e.Field,
				Description: fmt.Sprintf("required field %q is missing", e.Field),
				Paths:       []string{path},
				Value:       defaultVal,
			})
		}
	}
	return proposals
}

// extractEnumValue extracts the invalid value from a validation error message.
// The message format is: value "X" not in allowed values: [a, b, c]
func extractEnumValue(msg string, _ []string) string {
	start := strings.Index(msg, `"`)
	if start < 0 {
		return ""
	}
	end := strings.Index(msg[start+1:], `"`)
	if end < 0 {
		return ""
	}
	return msg[start+1 : start+1+end]
}

// closestMatch finds the closest string by Levenshtein distance.
func closestMatch(s string, candidates []string) string {
	if len(candidates) == 0 {
		return ""
	}

	best := candidates[0]
	bestDist := levenshtein(strings.ToLower(s), strings.ToLower(best))

	for _, c := range candidates[1:] {
		d := levenshtein(strings.ToLower(s), strings.ToLower(c))
		if d < bestDist {
			bestDist = d
			best = c
		}
	}
	return best
}

// levenshtein computes the edit distance between two strings.
func levenshtein(a, b string) int {
	la, lb := len(a), len(b)
	if la == 0 {
		return lb
	}
	if lb == 0 {
		return la
	}

	prev := make([]int, lb+1)
	curr := make([]int, lb+1)

	for j := 0; j <= lb; j++ {
		prev[j] = j
	}

	for i := 1; i <= la; i++ {
		curr[0] = i
		for j := 1; j <= lb; j++ {
			cost := 1
			if a[i-1] == b[j-1] {
				cost = 0
			}
			curr[j] = min(curr[j-1]+1, min(prev[j]+1, prev[j-1]+cost))
		}
		prev, curr = curr, prev
	}
	return prev[lb]
}
