// Package proposal implements the proposal analysis engine for rootline fix.
//
// It analyzes validation errors across multiple records and generates
// actionable proposals: extend enums, correct typos, add missing fields,
// migrate body values to frontmatter, and infer from child documents.
package proposal

import (
	"fmt"
	"strings"

	"github.com/pablontiv/rootline/internal/extract"
	"github.com/pablontiv/rootline/internal/rules"
)

// Type identifies the kind of proposal.
type Type string

const (
	ExtendEnum        Type = "extend_enum"
	MigrateValue      Type = "migrate_value"
	CorrectValue      Type = "correct_value"
	ExtractBody       Type = "extract_body"
	InferFromChildren Type = "infer_from_children"
	AddField          Type = "add_field"
)

// Proposal represents a suggested fix for one or more validation errors.
type Proposal struct {
	Type        Type     `json:"type"`
	Field       string   `json:"field"`
	Description string   `json:"description"`
	Paths       []string `json:"paths"`
	Value       string   `json:"value,omitempty"`
	From        string   `json:"from,omitempty"`
	To          string   `json:"to,omitempty"`
	WikiLinks   []string `json:"wiki_links,omitempty"`
}

// Report holds all proposals generated by Analyze.
type Report struct {
	Version   int        `json:"version"`
	Kind      string     `json:"kind"`
	Proposals []Proposal `json:"proposals"`
	Summary   Summary    `json:"summary"`
}

// Summary holds aggregate counts for a report.
type Summary struct {
	Total             int `json:"total"`
	ExtendEnum        int `json:"extend_enum"`
	MigrateValue      int `json:"migrate_value"`
	CorrectValue      int `json:"correct_value"`
	ExtractBody       int `json:"extract_body"`
	InferFromChildren int `json:"infer_from_children"`
	AddField          int `json:"add_field"`
}

// Analyze runs all detectors against validation errors and returns a Report.
func Analyze(records []*extract.Record, effective *rules.StemFile, errs map[string][]rules.ValidationError) *Report {
	var proposals []Proposal

	if effective != nil && len(errs) > 0 {
		// Phase 1: detect migrate_value first (needed to filter extend_enum and correct_value)
		migrateProposals := detectMigrateValue(effective, errs)

		// Build set of values that are migrate candidates (should not be added to enum).
		migrateValues := make(map[string]bool)
		for _, p := range migrateProposals {
			if p.From != "" {
				migrateValues[p.From] = true
			}
		}

		// Phase 1b: schema-level proposals — filter out values that should be migrated, not extended
		for _, p := range detectExtendEnum(effective, errs) {
			if migrateValues[p.Value] {
				continue // this value should be migrated, not added to enum
			}
			proposals = append(proposals, p)
		}

		// Phase 2: migrate_value has priority over correct_value for same path/field
		proposals = append(proposals, migrateProposals...)

		migratedKeys := make(map[string]bool)
		for _, p := range migrateProposals {
			for _, path := range p.Paths {
				migratedKeys[path+"\x00"+p.Field] = true
			}
		}
		for _, p := range detectCorrectValue(effective, errs) {
			skip := false
			for _, path := range p.Paths {
				if migratedKeys[path+"\x00"+p.Field] {
					skip = true
					break
				}
			}
			if !skip {
				proposals = append(proposals, p)
			}
		}

		// Phase 3: extract_body and infer_from_children have priority over add_field
		extractBodyProposals := detectExtractBody(records, effective, errs)
		inferProposals := detectInferFromChildren(records, effective, errs)
		proposals = append(proposals, extractBodyProposals...)
		proposals = append(proposals, inferProposals...)

		coveredKeys := make(map[string]bool)
		for _, p := range extractBodyProposals {
			for _, path := range p.Paths {
				coveredKeys[path+"\x00"+p.Field] = true
			}
		}
		for _, p := range inferProposals {
			for _, path := range p.Paths {
				coveredKeys[path+"\x00"+p.Field] = true
			}
		}
		for _, p := range detectAddField(effective, errs) {
			skip := false
			for _, path := range p.Paths {
				if coveredKeys[path+"\x00"+p.Field] {
					skip = true
					break
				}
			}
			if !skip {
				proposals = append(proposals, p)
			}
		}
	}

	summary := Summary{Total: len(proposals)}
	for _, p := range proposals {
		switch p.Type {
		case ExtendEnum:
			summary.ExtendEnum++
		case MigrateValue:
			summary.MigrateValue++
		case CorrectValue:
			summary.CorrectValue++
		case ExtractBody:
			summary.ExtractBody++
		case InferFromChildren:
			summary.InferFromChildren++
		case AddField:
			summary.AddField++
		}
	}

	return &Report{
		Version:   1,
		Kind:      "rootline/proposals",
		Proposals: proposals,
		Summary:   summary,
	}
}

// detectExtendEnum finds enum values rejected by validation that appear in
// N >= 2 records, suggesting the .stem schema should be extended.
func detectExtendEnum(effective *rules.StemFile, errs map[string][]rules.ValidationError) []Proposal {
	// Collect invalid enum values per field.
	type fieldValue struct {
		field string
		value string
	}
	counts := make(map[fieldValue][]string) // fieldValue -> list of paths

	for path, pathErrs := range errs {
		for _, e := range pathErrs {
			if e.Rule != "enum" {
				continue
			}
			sf, ok := effective.Schema[e.Field]
			if !ok {
				continue
			}
			// Extract the actual invalid value from the error message.
			// The error format is: "value %q not in allowed values: ..."
			val := extractEnumValue(e.Message, sf.Values)
			if val != "" {
				fv := fieldValue{field: e.Field, value: val}
				counts[fv] = append(counts[fv], path)
			}
		}
	}

	var proposals []Proposal
	for fv, paths := range counts {
		if len(paths) < 2 {
			continue
		}
		proposals = append(proposals, Proposal{
			Type:        ExtendEnum,
			Field:       fv.field,
			Description: fmt.Sprintf("value %q appears in %d records; consider adding to .stem enum", fv.value, len(paths)),
			Paths:       paths,
			Value:       fv.value,
		})
	}
	return proposals
}

// detectMigrateValue finds enum errors where the value contains structured
// information like "Pending (blocked by T001)" and proposes migration.
func detectMigrateValue(effective *rules.StemFile, errs map[string][]rules.ValidationError) []Proposal {
	var proposals []Proposal

	for path, pathErrs := range errs {
		for _, e := range pathErrs {
			if e.Rule != "enum" {
				continue
			}
			sf, ok := effective.Schema[e.Field]
			if !ok || len(sf.Values) == 0 {
				continue
			}
			val := extractEnumValue(e.Message, sf.Values)
			if val == "" {
				continue
			}
			base, targets, notes := ParseBlockingInfo(val)
			if len(targets) == 0 && len(notes) == 0 {
				continue // No parenthetical info — not a migrate_value candidate
			}

			// Find the closest valid enum value for the base.
			newValue := closestMatch(base, sf.Values)
			var wikiLinks []string
			for _, t := range targets {
				wikiLinks = append(wikiLinks, "[[blocks:"+t+"]]")
			}

			desc := fmt.Sprintf("migrate %q to %q", val, newValue)
			if len(notes) > 0 {
				desc += fmt.Sprintf(" (notes: %s)", strings.Join(notes, ", "))
			}

			proposals = append(proposals, Proposal{
				Type:        MigrateValue,
				Field:       e.Field,
				Description: desc,
				Paths:       []string{path},
				From:        val,
				To:          newValue,
				WikiLinks:   wikiLinks,
			})
		}
	}
	return proposals
}

// detectCorrectValue finds enum errors where the value is close to a valid one.
func detectCorrectValue(effective *rules.StemFile, errs map[string][]rules.ValidationError) []Proposal {
	var proposals []Proposal

	for path, pathErrs := range errs {
		for _, e := range pathErrs {
			if e.Rule != "enum" {
				continue
			}
			sf, ok := effective.Schema[e.Field]
			if !ok || len(sf.Values) == 0 {
				continue
			}
			val := extractEnumValue(e.Message, sf.Values)
			if val == "" {
				continue
			}
			closest := closestMatch(val, sf.Values)
			if closest != "" && closest != val {
				proposals = append(proposals, Proposal{
					Type:        CorrectValue,
					Field:       e.Field,
					Description: fmt.Sprintf("value %q is close to %q", val, closest),
					Paths:       []string{path},
					From:        val,
					To:          closest,
				})
			}
		}
	}
	return proposals
}

// detectExtractBody finds records with required field errors that have the value
// in the body text as a bold-colon pattern (e.g., **Estado**: Completada).
func detectExtractBody(records []*extract.Record, effective *rules.StemFile, errs map[string][]rules.ValidationError) []Proposal {
	var proposals []Proposal

	// Build a map of records by path for body access.
	recordMap := make(map[string]*extract.Record)
	for _, rec := range records {
		recordMap[rec.Path] = rec
	}

	for path, pathErrs := range errs {
		rec, ok := recordMap[path]
		if !ok || rec.Body == "" {
			continue
		}

		bodyFields := extract.ScanBodyFields(rec.Body)
		if len(bodyFields) == 0 {
			continue
		}

		for _, e := range pathErrs {
			if e.Rule != "required" {
				continue
			}
			bodyVal, found := bodyFields[e.Field]
			if !found {
				continue
			}

			// Map body value to canonical enum value.
			mapped := mapValue(bodyVal)

			// Validate mapped value against enum if applicable.
			sf, ok := effective.Schema[e.Field]
			if ok && len(sf.Values) > 0 {
				valid := false
				for _, v := range sf.Values {
					if v == mapped {
						valid = true
						break
					}
				}
				if !valid {
					// Try closest match.
					mapped = closestMatch(mapped, sf.Values)
				}
			}

			proposals = append(proposals, Proposal{
				Type:        ExtractBody,
				Field:       e.Field,
				Description: fmt.Sprintf("extract %q from body to frontmatter as %q", bodyVal, mapped),
				Paths:       []string{path},
				From:        bodyVal,
				To:          mapped,
			})
		}
	}
	return proposals
}

// detectInferFromChildren finds README files with missing required fields
// that can be inferred from child document estados.
func detectInferFromChildren(records []*extract.Record, effective *rules.StemFile, errs map[string][]rules.ValidationError) []Proposal {
	var proposals []Proposal

	// Build a map of records by path.
	recordMap := make(map[string]*extract.Record)
	for _, rec := range records {
		recordMap[rec.Path] = rec
	}

	for path, pathErrs := range errs {
		// Only README files are candidates for child inference.
		if !strings.HasSuffix(path, "README.md") {
			continue
		}

		// Check if body already has the field — if so, extract_body will handle it.
		rec, ok := recordMap[path]
		if ok && rec.Body != "" {
			bodyFields := extract.ScanBodyFields(rec.Body)
			hasBodyHint := false
			for _, e := range pathErrs {
				if e.Rule == "required" {
					if _, found := bodyFields[e.Field]; found {
						hasBodyHint = true
						break
					}
				}
			}
			if hasBodyHint {
				continue // extract_body will handle this
			}
		}

		// Find child records (same directory prefix, excluding the README itself).
		dir := strings.TrimSuffix(path, "README.md")
		var childEstados []string
		for _, child := range records {
			if child.Path == path {
				continue
			}
			if !strings.HasPrefix(child.Path, dir) {
				continue
			}
			if estado, ok := child.Frontmatter["estado"]; ok {
				if s, ok := estado.(string); ok {
					childEstados = append(childEstados, s)
				}
			}
		}

		if len(childEstados) == 0 {
			continue
		}

		for _, e := range pathErrs {
			if e.Rule != "required" || e.Field != "estado" {
				continue
			}
			inferred := InferEstado(childEstados)
			proposals = append(proposals, Proposal{
				Type:        InferFromChildren,
				Field:       e.Field,
				Description: fmt.Sprintf("infer %q from %d child documents", inferred, len(childEstados)),
				Paths:       []string{path},
				Value:       inferred,
			})
		}
	}
	return proposals
}

// detectAddField finds required fields that are missing from records.
func detectAddField(effective *rules.StemFile, errs map[string][]rules.ValidationError) []Proposal {
	var proposals []Proposal

	for path, pathErrs := range errs {
		for _, e := range pathErrs {
			if e.Rule != "required" {
				continue
			}
			sf, ok := effective.Schema[e.Field]
			if !ok {
				continue
			}
			defaultVal := sf.Default
			if defaultVal == "" && len(sf.Values) > 0 {
				defaultVal = sf.Values[0]
			}
			proposals = append(proposals, Proposal{
				Type:        AddField,
				Field:       e.Field,
				Description: fmt.Sprintf("required field %q is missing", e.Field),
				Paths:       []string{path},
				Value:       defaultVal,
			})
		}
	}
	return proposals
}

// extractEnumValue extracts the invalid value from a validation error message.
// Supports both quoted (value "X" ...) and unquoted (value X ...) formats.
func extractEnumValue(msg string, _ []string) string {
	// Try quoted format first: value "X" not in allowed values
	start := strings.Index(msg, `"`)
	if start >= 0 {
		end := strings.Index(msg[start+1:], `"`)
		if end >= 0 {
			return msg[start+1 : start+1+end]
		}
	}

	// Try unquoted format: value X is not in allowed values
	const prefix = "value "
	if !strings.HasPrefix(msg, prefix) {
		return ""
	}
	rest := msg[len(prefix):]
	end := strings.Index(rest, " is not in allowed")
	if end < 0 {
		return ""
	}
	return rest[:end]
}

// closestMatch finds the closest string by Levenshtein distance.
func closestMatch(s string, candidates []string) string {
	if len(candidates) == 0 {
		return ""
	}

	best := candidates[0]
	bestDist := levenshtein(strings.ToLower(s), strings.ToLower(best))

	for _, c := range candidates[1:] {
		d := levenshtein(strings.ToLower(s), strings.ToLower(c))
		if d < bestDist {
			bestDist = d
			best = c
		}
	}
	return best
}

// levenshtein computes the edit distance between two strings.
func levenshtein(a, b string) int {
	la, lb := len(a), len(b)
	if la == 0 {
		return lb
	}
	if lb == 0 {
		return la
	}

	prev := make([]int, lb+1)
	curr := make([]int, lb+1)

	for j := 0; j <= lb; j++ {
		prev[j] = j
	}

	for i := 1; i <= la; i++ {
		curr[0] = i
		for j := 1; j <= lb; j++ {
			cost := 1
			if a[i-1] == b[j-1] {
				cost = 0
			}
			curr[j] = min(curr[j-1]+1, min(prev[j]+1, prev[j-1]+cost))
		}
		prev, curr = curr, prev
	}
	return prev[lb]
}
