package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pablontiv/rootline/internal/rules"
)

func TestNewSectionSourceMaterializesRequiredSectionsAndValidates(t *testing.T) {
	dir := newSectionSourceProject(t, `schema:
  status:
    type: string
    required: true
    default: Open
  beta:
    type: string
    required: true
    source: 'body.section["### Beta"]'
  alpha:
    type: string
    required: true
    source: 'body.section["## Alpha"]'
    default: seeded alpha
  special:
    type: string
    required: true
    source: 'body.section["## Q&A: Plan #1"]'
  optional:
    type: string
    required: false
    source: 'body.section["## Optional"]'
`)
	target := filepath.Join(dir, "T001-task.md")

	if out, err := runCmd(t, "new", target); err != nil {
		t.Fatalf("new failed: %v\noutput: %s", err, out)
	}

	got := string(mustReadFile(t, target))
	want := "---\nstatus: Open\n---\n# T001 Task\n\n## Alpha\n\nseeded alpha\n\n## Q&A: Plan #1\n\n<!-- TODO -->\n\n### Beta\n\n<!-- TODO -->\n"
	if got != want {
		t.Fatalf("generated bytes mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
	for _, shadow := range []string{"alpha:", "beta:", "special:", "optional:"} {
		if strings.Contains(got, shadow) {
			t.Fatalf("source-backed field %q shadowed the body source in frontmatter:\n%s", shadow, got)
		}
	}
	if out, err := runCmd(t, "validate", target); err != nil {
		t.Fatalf("generated file must validate, err=%v\noutput: %s", err, out)
	}
}

func TestNewSectionSourceUsesRecordPathAwareSchema(t *testing.T) {
	dir := newSectionSourceProject(t, `schema:
  task_notes:
    type: string
    required: true
    match: "T*.md"
    source: 'body.section["## Task Notes"]'
  readme_notes:
    type: string
    required: true
    match: "README.md"
    source: 'body.section["## Readme Notes"]'
`)

	task := filepath.Join(dir, "T001-task.md")
	if out, err := runCmd(t, "new", task); err != nil {
		t.Fatalf("new task failed: %v\noutput: %s", err, out)
	}
	taskContent := string(mustReadFile(t, task))
	if !strings.Contains(taskContent, "## Task Notes") || strings.Contains(taskContent, "## Readme Notes") {
		t.Fatalf("task path did not receive path-filtered sections:\n%s", taskContent)
	}

	readme := filepath.Join(dir, "README.md")
	if out, err := runCmd(t, "new", readme); err != nil {
		t.Fatalf("new readme failed: %v\noutput: %s", err, out)
	}
	readmeContent := string(mustReadFile(t, readme))
	if !strings.Contains(readmeContent, "## Readme Notes") || strings.Contains(readmeContent, "## Task Notes") {
		t.Fatalf("README path did not receive path-filtered sections:\n%s", readmeContent)
	}
}

func TestNewSectionSourceProspectiveValidationPinsFrontmatterOverride(t *testing.T) {
	dir := newSectionSourceProject(t, `schema:
  notes:
    type: string
    required: true
    source: 'body.section["## Notes"]'
`)
	target := filepath.Join(dir, "T001-task.md")
	effective := mustResolveNewEffective(t, dir, target)

	nonemptyOverride := "---\nnotes: explicit override\n---\n# T001 Task\n"
	if err := validateProspectiveNewContent(rootCmd, target, nonemptyOverride, effective); err != nil {
		t.Fatalf("nonempty frontmatter override should validate: %v", err)
	}

	explicitEmpty := "---\nnotes: \n---\n# T001 Task\n"
	if err := validateProspectiveNewContent(rootCmd, target, explicitEmpty, effective); err == nil {
		t.Fatal("explicit empty source-backed frontmatter must not shadow the missing body source")
	}
}

func TestNewSectionSourceNoWriteOnSchemaMaterializationOrValidationFailure(t *testing.T) {
	tests := []struct {
		name string
		stem string
	}{
		{"duplicate missing source heading", `schema:
  alpha:
    type: string
    required: true
    source: 'body.section["## Shared"]'
  beta:
    type: string
    required: true
    source: 'body.section["## Shared"]'
`},
		{"legacy section declaration", `schema:
  notes:
    type: section
    required: true
`},
		{"invalid source declaration", `schema:
  notes:
    type: string
    required: true
    source: 'body.section["Notes"]'
`},
		{"invalid prospective ordinary frontmatter", `schema:
  status:
    type: enum
    required: true
    values: [Open, Closed]
`},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := newSectionSourceProject(t, tt.stem)
			target := filepath.Join(dir, "T001-task.md")

			out, err := runCmd(t, "new", target)
			if err == nil {
				t.Fatalf("expected new to fail, output: %s", out)
			}
			if _, statErr := os.Stat(target); !os.IsNotExist(statErr) {
				t.Fatalf("target should remain absent, stat err=%v", statErr)
			}

			existing := filepath.Join(dir, "existing.md")
			original := []byte("---\nstatus: keep\n---\n# Existing\n")
			mustWriteFile(t, existing, original, 0o644)
			out, err = runCmd(t, "new", existing, "--force")
			if err == nil {
				t.Fatalf("expected forced new to fail, output: %s", out)
			}
			if got := string(mustReadFile(t, existing)); got != string(original) {
				t.Fatalf("existing target changed after failed force\ngot: %q\nwant:%q", got, string(original))
			}
		})
	}
}

func mustResolveNewEffective(t *testing.T, dir, target string) *rules.StemFile {
	t.Helper()
	effective, err := rules.ResolveForRecord(dir, target)
	if err != nil {
		t.Fatal(err)
	}
	return effective
}

func newSectionSourceProject(t *testing.T, stemTail string) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.Mkdir(filepath.Join(dir, ".git"), 0o755); err != nil {
		t.Fatal(err)
	}
	mustWriteFile(t, filepath.Join(dir, ".stem"), []byte("version: 2\n"+stemTail), 0o644)
	declareTestBoundary(t, dir)
	return dir
}
