name: OpenSSF Scorecard

on:
  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  scorecard:
    uses: pablontiv/crossbeam/.github/workflows/scorecard.yml@v1
    permissions:
      contents: read
      security-events: write
      id-token: write
