name: OpenSSF Scorecard

on:
  schedule:
    - cron: '0 4 * * *'

permissions: read-all

jobs:
  scorecard:
    uses: pablontiv/crossbeam/.github/workflows/scorecard.yml@v1
    permissions:
      security-events: write
      id-token: write
