name: OpenSSF Scorecard

on:
  branch_protection_rule:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 6 * * 1'

permissions: read-all

jobs:
  scorecard:
    uses: pablontiv/crossbeam/.github/workflows/scorecard.yml@v1
    permissions:
      security-events: write
      id-token: write
